### ISSUE TITLE
cant change background

### ISSUE THREAD

**Issue by Lesturr** [CurimuChizu/CC-Themes#6]
I can only change the background when i click settings not the one where the chat is thats just clouds.
Heres the code i put in CSS.

 ```css
.app {
    background-image: url("https://www.walldevil.com/wallpapers/w05/redheads-anime-anime-sleeping-highschool-dxd-gremory-rias.jpg") !important;
    background-size: 1500px 900px !important;
    background-repeat: no-repeat !important;
}
/* Just change the link to whatever picture, including the `s` in `https` */

.callout-backdrop {
    opacity:0.9 !important;
    background: url("https://www.walldevil.com/wallpapers/w05/redheads-anime-anime-sleeping-highschool-dxd-gremory-rias.jpg") !important;
    background-size: 1500px 900px !important;
    background-repeat: no-repeat !important;
}
```
##<DIV ALIGN=CENTER><a href="https://github.com/CurimuChizu/CC-Themes/blob/master/CC-Themes/ReZero.theme.css">ReZero The Anime</a></div>
<DIV ALIGN=CENTER><b><i>A theme based Re:Zero kara Hajimeru Isekai Seikatsu anime (Up to date as of 9/10)</i></b>
<img src="http://i.imgur.com/rthaufN.jpg"/>
<img src="http://i.imgur.com/QhU9gvh.jpg"/>
<img src="https://a.pomf.cat/fawsxb.gif"/></div>

Code for the background picture:
```css
.app {
    background-image: url("https://www.walldevil.com/wallpapers/w05/redheads-anime-anime-sleeping-highschool-dxd-gremory-rias.jpg") !important; 
    background-size: cover !important;
}
/* Just change the link to whatever picture of Emelia, Rem, or Ram including the `s` in `https` */

.callout-backdrop {
    opacity:0.9!important;
    background: url("https://www.walldevil.com/wallpapers/w05/redheads-anime-anime-sleeping-highschool-dxd-gremory-rias.jpg")!important;
    background-size: cover !important;
    background-position: center !important;
}
```

>
